---

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden-cni/properties/experimental_proxy_redirect_cidr?
  value: '127.128.0.0/9'

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden-cni/properties/experimental_enable_ingress_proxy_redirect?
  value: true

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/proxy/ads_addresses?
  value: ["169.254.0.2:15010"]

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=bosh-dns-adapter/properties/internal_service_mesh_domains?
  value: ["istio.apps.internal"]

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/app_domains/-
  value:
    name: istio.apps.internal
    internal: true

